### ISSUE TITLE
How can I contribute to VMD development?

### ISSUE THREAD

**Issue by demetriusnunes** [julianshapiro/vmd#4]
Hi there Julian,

Awesome work man. We love velocity and VMD.

Although, we can't use VMD as we would like because of some CSS issues on our app (elements with overflow: hidden, onclick handlers, etc).

So, I tried to find VMD source code so we could fork and create pull request on those issues, but I couldn't find it.

Is it in another github repo?

Again, thanks for these awesome tools.

**Comment by julianshapiro** [comment]
Hey dude :)

If you leave me your email, I'll send you the source, and we can take it from there :)

**Comment by demetriusnunes** [comment]
Sure, I'm at gmail, same username as here.
